[GLOBAL]
pants_version = "2.13.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.lint.isort",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.typecheck.mypy",
    "pants.backend.awslambda.python",
]
use_deprecated_directory_cli_args_semantics = false
use_deprecated_pex_binary_run_semantics = false

[source]
root_patterns = ["/packages/*/src", "/packages/*/tests"]

[anonymous-telemetry]
enabled = true
repo_id = "02a6ed9b-169f-4935-aeee-7cb9d1b5716f"

[python]
tailor_pex_binary_targets = false
enable_resolves = true
interpreter_constraints = ["CPython<4,>=3.9"]

[repl]
shell = "ipython"
